apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service1
    labels:
        name: config-service1
        version: cluster1
    namespace: edge-namespace
data:
    conf.json: '{"processes":2,"threads":2,"endpoints":[{"name":"endpoint1","protocol":"http","execution_mode":"sequential","network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service2","port":"80","endpoint":"endpoint1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service2","port":"80","endpoint":"endpoint2","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}},{"name":"endpoint2","protocol":"http","execution_mode":"parallel","network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[]}}]}'
    service.proto: "syntax = \"proto3\";\n\n\nservice service1 {\n    \n    rpc endpoint1 (Request) returns (Response) {}\n    \n    rpc endpoint2 (Request) returns (Response) {}\n    \n}\n\nservice service2 {\n    \n    rpc endpoint1 (Request) returns (Response) {}\n    \n    rpc endpoint2 (Request) returns (Response) {}\n    \n}\n\n\nmessage Request {\n    string data = 1;\n}\n\nmessage Response {\n    string data = 1;\n}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service1
    namespace: edge-namespace
    labels:
        version: cluster1
spec:
    selector:
        matchLabels:
            app: service1
            version: cluster1
    replicas: 1
    template:
        metadata:
            labels:
                app: service1
                version: cluster1
        spec:
            nodeName: cluster1-control-plane
            containers:
                - name: app
                  image: app-demo:latest
                  imagePullPolicy: Never
                  env:
                    - name: SERVICE_NAME
                      value: service1
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/app/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 1
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 2000m
                        memory: 1024M
                    requests:
                        cpu: 2000m
                        memory: 1024M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service1
---
apiVersion: v1
kind: Service
metadata:
    name: service1
    namespace: edge-namespace
    labels:
        version: cluster1
    annotations:
        http: /
spec:
    selector:
        app: service1
    ports:
        - name: http
          port: 80
          targetPort: 5000
