apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service2
    labels:
        name: config-service2
        version: cluster1
    namespace: default
data:
    conf.json: '{"processes":2,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"parallel","cpu_complexity":{"execution_time":1,"threads":2},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":null}},{"name":"endpoint2","execution_mode":"parallel","network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":null}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service2
    namespace: default
    labels:
        version: cluster1
spec:
    selector:
        matchLabels:
            app: service2
            version: cluster1
    template:
        metadata:
            labels:
                app: service2
                version: cluster1
            annotations: {}
        spec:
            nodeName: cluster1-control-plane
            containers:
                - name: app
                  image: hydragen-emulator:5033c2d8
                  imagePullPolicy: Never
                  env:
                    - name: SERVICE_NAME
                      value: service2
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 1
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 2000m
                        memory: 1024M
                    requests:
                        cpu: 2000m
                        memory: 1024M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service2
---
apiVersion: v1
kind: Service
metadata:
    name: service2
    namespace: default
    labels:
        version: cluster1
    annotations:
        http: /
spec:
    selector:
        app: service2
    ports:
        - name: http
          port: 80
          targetPort: 5000
