apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service2
    labels:
        name: config-service2
        version: cluster4
    namespace: namespace2
data:
    conf.json: '{"processes":1,"logging":false,"endpoints":[{"name":"end1","protocol":"http","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1,"lock_threads":false},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service3","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}},{"name":"end2","protocol":"http","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1,"lock_threads":false},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service3","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service4","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service5","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}},{"name":"end3","protocol":"http","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1,"lock_threads":false},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service3","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service4","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service5","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service6","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service7","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}}]}'
    service.proto: "syntax = \"proto3\";\n\n\nservice service1 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n    rpc end2 (Request) returns (Response) {}\n    \n    rpc end3 (Request) returns (Response) {}\n    \n}\n\nservice service2 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n    rpc end2 (Request) returns (Response) {}\n    \n    rpc end3 (Request) returns (Response) {}\n    \n}\n\nservice service3 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n}\n\nservice service4 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n    rpc end2 (Request) returns (Response) {}\n    \n    rpc end3 (Request) returns (Response) {}\n    \n}\n\nservice service5 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n}\n\nservice service6 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n    rpc end2 (Request) returns (Response) {}\n    \n    rpc end3 (Request) returns (Response) {}\n    \n}\n\nservice service7 {\n    \n    rpc end1 (Request) returns (Response) {}\n    \n    rpc end2 (Request) returns (Response) {}\n    \n}\n\n\nmessage Request {\n    string data = 1;\n}\n\nmessage Response {\n    string data = 1;\n}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service2
    namespace: namespace2
    labels:
        version: cluster4
spec:
    selector:
        matchLabels:
            app: service2
            version: cluster4
    replicas: 3
    template:
        metadata:
            labels:
                app: service2
                version: cluster4
            annotations: {}
        spec:
            containers:
                - name: app
                  image: ghcr.io/ericssonresearch/cloud-native-app-simulator/app-demo:v3.0.1
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: SERVICE_NAME
                      value: service2
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/app/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 2
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 500m
                        memory: 256M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service2
---
apiVersion: v1
kind: Service
metadata:
    name: service2
    namespace: namespace2
    labels:
        version: cluster4
    annotations:
        http: /
spec:
    selector:
        app: service2
    ports:
        - name: http
          port: 80
          targetPort: 5000
