apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service3
    labels:
        name: config-service3
        version: cluster3
    namespace: namespace1
data:
    conf.json: '{"processes":1,"logging":false,"protocol":"http","endpoints":[{"name":"end1","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[]}},{"name":"end2","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service4","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service5","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service6","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service7","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256},{"service":"service8","port":80,"endpoint":"end1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service3
    namespace: namespace1
    labels:
        version: cluster3
spec:
    selector:
        matchLabels:
            app: service3
            version: cluster3
    replicas: 1
    template:
        metadata:
            labels:
                app: service3
                version: cluster3
            annotations: {}
        spec:
            containers:
                - name: app
                  image: hydragen-emulator:807af6cb
                  imagePullPolicy: Never
                  env:
                    - name: SERVICE_NAME
                      value: service3
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 2
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 500m
                        memory: 256M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service3
---
apiVersion: v1
kind: Service
metadata:
    name: service3
    namespace: namespace1
    labels:
        version: cluster3
    annotations:
        http: /
spec:
    selector:
        app: service3
    ports:
        - name: http
          port: 80
          targetPort: 5000
